// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/accounting/client.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	accounting "bitbucket.org/Amartha/go-megatron/internal/pkg/accounting"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetAccountByAccountNumber mocks base method.
func (m *MockClient) GetAccountByAccountNumber(ctx context.Context, accountNumber string) (accounting.ResponseGetAccountByAccountNumber, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByAccountNumber", ctx, accountNumber)
	ret0, _ := ret[0].(accounting.ResponseGetAccountByAccountNumber)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByAccountNumber indicates an expected call of GetAccountByAccountNumber.
func (mr *MockClientMockRecorder) GetAccountByAccountNumber(ctx, accountNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByAccountNumber", reflect.TypeOf((*MockClient)(nil).GetAccountByAccountNumber), ctx, accountNumber)
}

// GetAccountByAccountNumberOrLegacyID mocks base method.
func (m *MockClient) GetAccountByAccountNumberOrLegacyID(ctx context.Context, accountNumber string) (accounting.ResponseGetAccountByAccountNumber, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByAccountNumberOrLegacyID", ctx, accountNumber)
	ret0, _ := ret[0].(accounting.ResponseGetAccountByAccountNumber)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByAccountNumberOrLegacyID indicates an expected call of GetAccountByAccountNumberOrLegacyID.
func (mr *MockClientMockRecorder) GetAccountByAccountNumberOrLegacyID(ctx, accountNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByAccountNumberOrLegacyID", reflect.TypeOf((*MockClient)(nil).GetAccountByAccountNumberOrLegacyID), ctx, accountNumber)
}

// GetAccountByLegacyID mocks base method.
func (m *MockClient) GetAccountByLegacyID(ctx context.Context, legacyID string) (accounting.ResponseGetAccountByAccountNumber, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByLegacyID", ctx, legacyID)
	ret0, _ := ret[0].(accounting.ResponseGetAccountByAccountNumber)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByLegacyID indicates an expected call of GetAccountByLegacyID.
func (mr *MockClientMockRecorder) GetAccountByLegacyID(ctx, legacyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByLegacyID", reflect.TypeOf((*MockClient)(nil).GetAccountByLegacyID), ctx, legacyID)
}

// GetAccountsByParams mocks base method.
func (m *MockClient) GetAccountsByParams(ctx context.Context, in accounting.DoGetAllAccountNumbersByParamRequest) (map[string][]accounting.GetAllAccountNumbersByParam, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountsByParams", ctx, in)
	ret0, _ := ret[0].(map[string][]accounting.GetAllAccountNumbersByParam)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountsByParams indicates an expected call of GetAccountsByParams.
func (mr *MockClientMockRecorder) GetAccountsByParams(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountsByParams", reflect.TypeOf((*MockClient)(nil).GetAccountsByParams), ctx, in)
}

// GetEntityByParams mocks base method.
func (m *MockClient) GetEntityByParams(ctx context.Context, in accounting.DoGetEntityByParamsRequest) (accounting.DoGetEntityResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntityByParams", ctx, in)
	ret0, _ := ret[0].(accounting.DoGetEntityResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntityByParams indicates an expected call of GetEntityByParams.
func (mr *MockClientMockRecorder) GetEntityByParams(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntityByParams", reflect.TypeOf((*MockClient)(nil).GetEntityByParams), ctx, in)
}

// GetInvestedAccountNumber mocks base method.
func (m *MockClient) GetInvestedAccountNumber(ctx context.Context, cihAccountNumber string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvestedAccountNumber", ctx, cihAccountNumber)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvestedAccountNumber indicates an expected call of GetInvestedAccountNumber.
func (mr *MockClientMockRecorder) GetInvestedAccountNumber(ctx, cihAccountNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvestedAccountNumber", reflect.TypeOf((*MockClient)(nil).GetInvestedAccountNumber), ctx, cihAccountNumber)
}

// GetJournalDetail mocks base method.
func (m *MockClient) GetJournalDetail(ctx context.Context, transactionId string) (accounting.ResponseGetJournalDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJournalDetail", ctx, transactionId)
	ret0, _ := ret[0].(accounting.ResponseGetJournalDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJournalDetail indicates an expected call of GetJournalDetail.
func (mr *MockClientMockRecorder) GetJournalDetail(ctx, transactionId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJournalDetail", reflect.TypeOf((*MockClient)(nil).GetJournalDetail), ctx, transactionId)
}

// GetLoanPartnerAccountByParams mocks base method.
func (m *MockClient) GetLoanPartnerAccountByParams(ctx context.Context, in accounting.DoGetLoanPartnerAccountByParamsRequest) (accounting.DoGetLoanPartnerAccountByParamsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoanPartnerAccountByParams", ctx, in)
	ret0, _ := ret[0].(accounting.DoGetLoanPartnerAccountByParamsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoanPartnerAccountByParams indicates an expected call of GetLoanPartnerAccountByParams.
func (mr *MockClientMockRecorder) GetLoanPartnerAccountByParams(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoanPartnerAccountByParams", reflect.TypeOf((*MockClient)(nil).GetLoanPartnerAccountByParams), ctx, in)
}

// GetReceivableAccountNumber mocks base method.
func (m *MockClient) GetReceivableAccountNumber(ctx context.Context, cihAccountNumber string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReceivableAccountNumber", ctx, cihAccountNumber)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReceivableAccountNumber indicates an expected call of GetReceivableAccountNumber.
func (mr *MockClientMockRecorder) GetReceivableAccountNumber(ctx, cihAccountNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceivableAccountNumber", reflect.TypeOf((*MockClient)(nil).GetReceivableAccountNumber), ctx, cihAccountNumber)
}
