// Code generated by MockGen. DO NOT EDIT.
// Source: internal/rules/loader.go
//
// Generated by this command:
//
//	mockgen -source=internal/rules/loader.go -destination=internal/rules/mock/rules_loader_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	pkg "github.com/hyperjumptech/grule-rule-engine/pkg"
	gomock "go.uber.org/mock/gomock"
)

// MockRuleLoader is a mock of RuleLoader interface.
type MockRuleLoader struct {
	ctrl     *gomock.Controller
	recorder *MockRuleLoaderMockRecorder
}

// MockRuleLoaderMockRecorder is the mock recorder for MockRuleLoader.
type MockRuleLoaderMockRecorder struct {
	mock *MockRuleLoader
}

// NewMockRuleLoader creates a new mock instance.
func NewMockRuleLoader(ctrl *gomock.Controller) *MockRuleLoader {
	mock := &MockRuleLoader{ctrl: ctrl}
	mock.recorder = &MockRuleLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleLoader) EXPECT() *MockRuleLoaderMockRecorder {
	return m.recorder
}

// LoadRule mocks base method.
func (m *MockRuleLoader) LoadRule(name, env, version string) (pkg.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadRule", name, env, version)
	ret0, _ := ret[0].(pkg.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadRule indicates an expected call of LoadRule.
func (mr *MockRuleLoaderMockRecorder) LoadRule(name, env, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadRule", reflect.TypeOf((*MockRuleLoader)(nil).LoadRule), name, env, version)
}
