// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/dddnotification/client.go
//
// Generated by this command:
//
//	mockgen -source=./internal/pkg/dddnotification/client.go -destination=./internal/pkg/dddnotification/mock/client_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dddnotification "bitbucket.org/Amartha/go-megatron/internal/pkg/dddnotification"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// SendMessageToSlack mocks base method.
func (m *MockClient) SendMessageToSlack(ctx context.Context, message dddnotification.MessageData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessageToSlack", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessageToSlack indicates an expected call of SendMessageToSlack.
func (mr *MockClientMockRecorder) SendMessageToSlack(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageToSlack", reflect.TypeOf((*MockClient)(nil).SendMessageToSlack), ctx, message)
}
