// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/kafka/publisher.go
//
// Generated by this command:
//
//	mockgen -source=internal/pkg/kafka/publisher.go -destination=internal/pkg/kafka/mock/publisher_mock.go -package=mock
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	messaging "bitbucket.org/Amartha/go-payment-lib/messaging"
	gomock "go.uber.org/mock/gomock"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// ClosePublisher mocks base method.
func (m *MockPublisher) ClosePublisher() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClosePublisher")
	ret0, _ := ret[0].(error)
	return ret0
}

// ClosePublisher indicates an expected call of ClosePublisher.
func (mr *MockPublisherMockRecorder) ClosePublisher() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClosePublisher", reflect.TypeOf((*MockPublisher)(nil).ClosePublisher))
}

// PublishAsyncWithKey mocks base method.
func (m *MockPublisher) PublishAsyncWithKey(ctx context.Context, topic, key string, body any, opts ...messaging.PublishOption) (*messaging.Promise, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, topic, key, body}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PublishAsyncWithKey", varargs...)
	ret0, _ := ret[0].(*messaging.Promise)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishAsyncWithKey indicates an expected call of PublishAsyncWithKey.
func (mr *MockPublisherMockRecorder) PublishAsyncWithKey(ctx, topic, key, body any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, topic, key, body}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishAsyncWithKey", reflect.TypeOf((*MockPublisher)(nil).PublishAsyncWithKey), varargs...)
}

// PublishAsyncWithKeyAndHeader mocks base method.
func (m *MockPublisher) PublishAsyncWithKeyAndHeader(ctx context.Context, topic, key string, body any, headers map[string]any, opts ...messaging.PublishOption) (*messaging.Promise, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, topic, key, body, headers}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PublishAsyncWithKeyAndHeader", varargs...)
	ret0, _ := ret[0].(*messaging.Promise)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishAsyncWithKeyAndHeader indicates an expected call of PublishAsyncWithKeyAndHeader.
func (mr *MockPublisherMockRecorder) PublishAsyncWithKeyAndHeader(ctx, topic, key, body, headers any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, topic, key, body, headers}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishAsyncWithKeyAndHeader", reflect.TypeOf((*MockPublisher)(nil).PublishAsyncWithKeyAndHeader), varargs...)
}

// PublishSyncWithKey mocks base method.
func (m *MockPublisher) PublishSyncWithKey(ctx context.Context, topic, key string, body any, opts ...messaging.PublishOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, topic, key, body}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PublishSyncWithKey", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishSyncWithKey indicates an expected call of PublishSyncWithKey.
func (mr *MockPublisherMockRecorder) PublishSyncWithKey(ctx, topic, key, body any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, topic, key, body}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSyncWithKey", reflect.TypeOf((*MockPublisher)(nil).PublishSyncWithKey), varargs...)
}

// PublishSyncWithKeyAndHeader mocks base method.
func (m *MockPublisher) PublishSyncWithKeyAndHeader(ctx context.Context, topic, key string, body any, headers map[string]any, opts ...messaging.PublishOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, topic, key, body, headers}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PublishSyncWithKeyAndHeader", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishSyncWithKeyAndHeader indicates an expected call of PublishSyncWithKeyAndHeader.
func (mr *MockPublisherMockRecorder) PublishSyncWithKeyAndHeader(ctx, topic, key, body, headers any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, topic, key, body, headers}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSyncWithKeyAndHeader", reflect.TypeOf((*MockPublisher)(nil).PublishSyncWithKeyAndHeader), varargs...)
}

// PublishSyncWithKeyAndLog mocks base method.
func (m *MockPublisher) PublishSyncWithKeyAndLog(ctx context.Context, description, topic, key string, data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishSyncWithKeyAndLog", ctx, description, topic, key, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishSyncWithKeyAndLog indicates an expected call of PublishSyncWithKeyAndLog.
func (mr *MockPublisherMockRecorder) PublishSyncWithKeyAndLog(ctx, description, topic, key, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSyncWithKeyAndLog", reflect.TypeOf((*MockPublisher)(nil).PublishSyncWithKeyAndLog), ctx, description, topic, key, data)
}
